### ISSUE TITLE
Unit tests fail on Node 8

### ISSUE THREAD

**Issue by rhoggSugarcrm** [sugarcrm/thorn#170]
``` 
57 passing (6s)
12 failing

  1) Thorn Fixtures creation should create a fixture:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:130:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  2) Thorn Fixtures creation should create a fixture using options.module:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:167:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  3) Thorn Fixtures creation should create multiple fixtures:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:259:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  4) Thorn Fixtures linking should create fixtures and link them:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:452:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  5) Thorn Fixtures linking should retry fixture creation and linking on 401's:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:495:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  6) Thorn Fixtures linking with pre-existing records should link records:
     Uncaught AssertionError: expected undefined to equal 'Fixtures'
      at Interceptor.body (tests/index.js:536:68)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  7) Thorn Agent request methods should send GET request:
     Uncaught AssertionError: expected undefined to equal 'Agent-foo'
      at Interceptor.body (tests/index.js:882:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:566:14)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  8) Thorn Agent request methods should send POST request:
     Uncaught AssertionError: expected undefined to equal 'Agent-foo'
      at Interceptor.body (tests/index.js:900:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  9) Thorn Agent request methods should send PUT request:
     Uncaught AssertionError: expected undefined to equal 'Agent-foo'
      at Interceptor.body (tests/index.js:920:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  10) Thorn Agent request methods should send DELETE request:
     Uncaught AssertionError: expected undefined to equal 'Agent-foo'
      at Interceptor.body (tests/index.js:940:64)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  11) Utils login should post to the login endpoint with the right params:
     Uncaught AssertionError: expected undefined to equal 'TestHeader'
      at Interceptor.body (tests/utils.js:61:60)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)

  12) Utils refresh should post to the refresh endpoint with the right params:
     Uncaught AssertionError: expected undefined to equal 'TestHeader'
      at Interceptor.body (tests/utils.js:102:60)
      at end (node_modules/nock/lib/request_overrider.js:321:34)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.end (node_modules/request/request.js:1438:14)
      at end (node_modules/request/request.js:553:16)
      at Immediate.<anonymous> (node_modules/request/request.js:580:7)
```

**Comment by rhoggSugarcrm** [comment]
This is an upstream issue related to https://github.com/node-nock/nock/issues/922

**Comment by rhoggSugarcrm** [comment]
This is fixed by https://github.com/node-nock/nock/pull/929, we just need to wait for nock to make a new release and we can update the dependency.

**Comment by rhoggSugarcrm** [comment]
nock has made a new release, now we just have to update it. #178 does so.
